#!/bin/bash

# Usage: csvify --project PROJECT ROOT

while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
	--project) # cmip5, cmip6
	    project="$2"
	    shift
	    shift
	    ;;
	*)
	    root="$1"
	    shift
	    ;;
    esac
done

tocsv_cmip5() {
  awk -v root="$1" '
  BEGIN{
    # Header
    print "project,product,model,experiment,ensemble,table,variable,size,last_modification,file"
  }
  {
    drs=$1
    sub(root,"",drs)
    n=split(drs, facets, "/")
    project="cmip5"
    product=facets[2]
    institute=facets[3]
    frequency=facets[6]

    # filename is always the last facet
    # in cmip5 sometimes variable is in the DRS and sometimes its not, why?
    filename=facets[n]

    sub(".nc","",filename) # Remove extension
    split(filename, fparts, "_")
    variable=fparts[1]
    table=fparts[2]
    model=fparts[3]
    experiment=fparts[4]
    ensemble=fparts[5]

    print project","product","model","experiment","ensemble","table","variable","$2","$3","$1
  }'
}

tocsv_cmip6() {
  awk -v root="$1" '
  BEGIN {
    # Header
    print "project,activity_id,institution_id,source_id,experiment_id,variant_label,table_id,variable_id,grid_label,version,size,last_modification,file"
  }
  {
    drs=$1
    sub(root,"",drs)
    n=split(drs,facets,"/")
    project="cmip6"
    activity_id=facets[3]
    institution_id=facets[4]
    source_id=facets[5]
    experiment_id=facets[6]
    variant_label=facets[7]
    table_id=facets[8]
    variable_id=facets[9]
    grid_label=facets[10]
    version=facets[11]
    filename=facets[n]

    print project","activity_id","institution_id","source_id","experiment_id","variant_label","table_id","variable_id","grid_label","version","$2","$3","$1
  }'
}

< /dev/stdin xargs stat -c '%n %s %Y' | tocsv_${project} $root
